In [2]:
 # 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

# 3x3 Array and Transpose:
import numpy as np
arr = np.random.randint(1, 101, (3, 3))
print(arr)
print(arr.T)  # Interchanged rows and columns


[[38 27 62]
 [22 77 80]
 [61 32 23]]
[[38 22 61]
 [27 77 32]
 [62 80 23]]


In [4]:
 # 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
# 1D to 2D and 2D to 5x2:

arr = np.arange(10)
arr_2x5 = arr.reshape(2, 5)
arr_5x2 = arr.reshape(5, 2)
print(arr_2x5)
print(arr_5x2)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [5]:
 # 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
# 4x4 Array with Border:

arr = np.random.rand(4, 4)
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr_with_border)


[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.46920447 0.20220332 0.15423592 0.34204758 0.        ]
 [0.         0.42552798 0.17365341 0.77961091 0.19261237 0.        ]
 [0.         0.7024473  0.88446794 0.93094212 0.67600168 0.        ]
 [0.         0.02671028 0.81524705 0.29436145 0.25755243 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [6]:
 # 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
# Array with Step:

arr = np.arange(10, 65, 5)
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


In [7]:
#  5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
# (uppercase, lowercase, title case, etc.) to each element.

# Case Transformations:
arr = np.array(['python', 'numpy', 'pandas'])
uppercase = np.char.upper(arr)
lowercase = np.char.lower(arr)
titlecase = np.char.title(arr)
print(uppercase, lowercase, titlecase)


['PYTHON' 'NUMPY' 'PANDAS'] ['python' 'numpy' 'pandas'] ['Python' 'Numpy' 'Pandas']


In [9]:
#  6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

# Insert Spaces:
words = np.array(['hello', 'world'])
spaced_words = np.array([' '.join(list(word)) for word in words])
print(spaced_words)


['h e l l o' 'w o r l d']


In [10]:
 # 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

# Element-wise Operations:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
add = a + b
sub = a - b
mul = a * b
div = a / b
print(add, sub, mul, div)


[[ 6  8]
 [10 12]] [[-4 -4]
 [-4 -4]] [[ 5 12]
 [21 32]] [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [12]:
#  8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

# Identity Matrix and Diagonal:
identity = np.eye(5)
diagonal = np.diag(identity)
print(diagonal)


[1. 1. 1. 1. 1.]


In [14]:
#  9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
# this array.

# Find Primes:
arr = np.random.randint(0, 1001, 100)
primes = [num for num in arr if num > 1 and all(num % i != 0 for i in range(2, int(np.sqrt(num)) + 1))]
print(primes)


[227, 281, 911, 443, 137, 337, 167, 499, 821, 883, 311, 139, 113, 757, 773, 857, 307, 907, 853, 163, 587]


In [16]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
# averages.
# Weekly Averages:

temps = np.random.randint(15, 35, 30)  # Example daily temperatures
weekly_avg = [np.mean(temps[i:i+7]) for i in range(0, 30, 7)]
print(weekly_avg)


[23.571428571428573, 25.285714285714285, 26.571428571428573, 27.142857142857142, 31.0]
