In [2]:
#  1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it 
# enhance Python's capabilities for numerical operations?

# NumPy in Scientific Computing and Data Analysis:

# Purpose: NumPy provides powerful tools for numerical computing. It includes support for arrays, matrices, and a vast collection of mathematical functions to operate on these data structures efficiently.

# Advantages:

# Performance: NumPy's operations are highly optimized and executed in compiled C code.

# Convenience: Supports extensive functionality like linear algebra, random number generation, Fourier transforms, and more.

# Integration: Works seamlessly with other libraries like SciPy, Pandas, and Matplotlib.

# Memory Efficiency: Uses contiguous memory blocks for arrays, making operations on large datasets faster.

In [3]:
#  2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the 
# other?

# np.mean() vs np.average():

# np.mean(): Calculates the arithmetic mean along the specified axis.

# np.average(): Computes the weighted average if weights are provided, otherwise behaves like np.mean().

# When to use: Use np.mean() for a straightforward average calculation. Use np.average() when different elements have different significance.


In [4]:

import numpy as np
data = np.array([1, 2, 3, 4, 5])
print(np.mean(data))  # 3.0
print(np.average(data, weights=[1, 2, 3, 4, 5]))  # 3.6667

3.0
3.6666666666666665


In [5]:
#  3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D 
# arrays.
# Reversing a NumPy Array:

# 1D Array:
arr = np.array([1, 2, 3, 4, 5])
print(arr[::-1])  # [5, 4, 3, 2, 1]


[5 4 3 2 1]


In [6]:
# 2D Array:

# Reverse rows:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr[::-1])
# [[5, 6]
#  [3, 4]
#  [1, 2]]


[[5 6]
 [3 4]
 [1 2]]


In [7]:
# Reverse columns:
print(arr[:, ::-1])
# [[2, 1]
#  [4, 3]
#  [6, 5]]


[[2 1]
 [4 3]
 [6 5]]


In [10]:
#  4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types 
# in memory management and performance.

# Determining Data Type in NumPy:

# Method: Use dtype attribute.
arr = np.array([1, 2, 3])
print(arr.dtype)  # int64
# Importance: Data types determine how much memory is allocated and how data is interpreted,
# affecting both performance and memory usage.



int32


In [11]:
 # 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

# ndarrays in NumPy:

# Definition: The ndarray (n-dimensional array) is a core data structure in NumPy, allowing for efficient array manipulation.

# Key Features:

# Homogeneity: All elements must be of the same type.

# Multidimensional: Can handle more than one dimension.

# Broadcasting: Supports element-wise operations.

# Difference from Python Lists:

# Fixed size and type.

# Better performance for numerical operations.

In [13]:
 # 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

# Performance Benefits of NumPy Arrays:

# Speed: NumPy operations are performed using optimized C code, leading to significant performance improvements.

# Memory Usage: NumPy arrays use less memory by storing elements in contiguous blocks.
import time
list1 = list(range(100000))
array1 = np.array(list1)


In [14]:
#  7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and 
# output.
# vstack(): Stacks arrays vertically (row-wise).

# hstack(): Stacks arrays horizontally (column-wise).

a = np.array([1, 2])
b = np.array([3, 4])
print(np.vstack((a, b)))
# [[1, 2]
#  [3, 4]]
print(np.hstack((a, b)))
# [1, 2, 3, 4]


[[1 2]
 [3 4]]
[1 2 3 4]


In [15]:
#  8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various 
# array dimensions.

# fliplr() vs flipud():

# fliplr(): Flips array left-right.

# flipud(): Flips array up-down.

In [16]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(np.fliplr(arr))
# [[2, 1]
#  [4, 3]
#  [6, 5]]
print(np.flipud(arr))
# [[5, 6]
#  [3, 4]
#  [1, 2]]


[[2 1]
 [4 3]
 [6 5]]
[[5 6]
 [3 4]
 [1 2]]


In [17]:
 # 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

# array_split():

# Functionality: Splits an array into multiple sub-arrays.

# Uneven Splits: It handles uneven splits by distributing the extra elements to the earlier sub-arrays.

In [18]:
arr = np.array([1, 2, 3, 4, 5])
print(np.array_split(arr, 3))
# [array([1, 2]), array([3, 4]), array([5])]


[array([1, 2]), array([3, 4]), array([5])]


In [21]:
#  10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array 
# operations?

# Vectorization and Broadcasting:

# Vectorization: Allows for operations on entire arrays without explicit loops, enhancing speed.

# Broadcasting: Enables operations on arrays of different shapes by expanding them to a common shape.

In [22]:
a = np.array([1, 2, 3])
b = np.array([4])
print(a + b)  # [5, 6, 7]


[5 6 7]
